#ifndef GLOBALCONFIG_H
#define GLOBALCONFIG_H
#include <Arduino.h>

#define LED_PIN D1
#define RING_LED_PIN_ROW_01 D1
#define RING_LED_PIN_ROW_02 D2
#define RING_LED_PIN_ROW_03 D3
#define RING_LED_PIN_ROW_04 D4

#define CONFIG_MAP_SIZE 16
#define CONFIG_DIMENSION_X 4
#define CONFIG_DIMENSION_Y 4

#define NUM_RING_ALL_PIX 384
#define NUM_RING_ONE_PIX 24



#endif
